select * from emp;
select sysdate from dual;
SELECT * FROM EMP
WHERE JOB = 'MANAGER';
SELECT ENAME, SAL FROM EMP
WHERE SAL>2000;

SELECT DISTINCT JOB FROM EMP; 
SELECT JOB FROM EMP;
SELECT DISTINCT JOB, DEPTNO FROM EMP;
SELECT JOB, DEPTNO FROM EMP;