SELECT * FROM EMP;
SELECT ENAME AS "사원이름" FROM EMP;
SELECT JOB AS "직업" FROM EMP;
SELECT SAL AS "월급" FROM EMP;
SELECT EMPNO "사원번호", ENAME AS "이름", JOB AS "직업" FROM EMP;
SELECT ENAME AS "이름", SAL * 12 AS "연봉*상여금 및 미포함" FROM EMP;
SELECT COMM AS "상여금" FROM EMP;
SELECT MGR AS "직속상관-사원번호" FROM EMP;
SELECT DEPTNO "부서번호" FROM EMP;
SELECT EMPNO "사원번호" FROM EMP;
SELECT HIREDATE "회사입사일" FROM EMP;
SELECT EMPNO "사원번호", ENAME "이름", SAL "급여" FROM EMP;
SELECT EMPNO "사원번호", ENAME AS "이름", SAL * 12 AS "연봉*상여금 및 미포함" FROM EMP;
SELECT EMPNO "사원번호", ENAME AS "이름", HIREDATE "회사입사일", SAL * 12 AS "연봉*상여금 및 미포함" FROM EMP;
SELECT EMPNO "사원번호", ENAME AS "이름", JOB AS "직업", SAL * 12 AS "연봉*상여금 및 미포함" FROM EMP;
SELECT EMPNO "사원번호", ENAME AS "이름", JOB AS "직업", MGR AS "직속상관-사원번호", SAL * 12 AS "연봉*상여금 및 미포함" FROM EMP;
SELECT EMPNO "사원번호", ENAME AS "이름", JOB AS "직업", MGR AS "직속상관-사원번호", HIREDATE "회사입사일", SAL * 12 AS "연봉*상여금 및 미포함" FROM EMP;
SELECT EMPNO "사원번호", ENAME AS "이름", JOB AS "직업", MGR AS "직속상관-사원번호", HIREDATE "회사입사일", SAL * 12 AS "연봉*상여금 및 미포함", DEPTNO AS "부서번호" FROM EMP;
SELECT EMPNO AS "사원번호", ENAME AS "이름", JOB AS "직업", MGR AS "직속상관-사원번호", HIREDATE AS "회사입사일", SAL AS "급여", COMM AS "상여금", DEPTNO AS "부서번호" FROM EMP;