SELECT * FROM EMP;
SELECT ENAME, LENGTH(ENAME) AS 이름길이 FROM EMP WHERE LENGTH(ENAME) = 5;
SELECT JOB, LENGTH(JOB) AS 직업명길이 FROM EMP WHERE LENGTH(JOB) = 7;
SELECT ENAME, HIREDATE FROM EMP WHERE SUBSTR(HIREDATE, 1, 2) = '87';
SELECT ENAME, INSTR(ENAME, 'A') AS A의위치 FROM EMP;
SELECT JOB, INSTR(JOB, 'K') AS K의위치 FROM EMP;
SELECT ENAME, REPLACE(ENAME, 'S') FROM EMP;