SELECT * FROM EMP; 
SELECT JOB, SUM(SAL) AS "급여 합계" FROM EMP GROUP BY JOB;
SELECT DEPTNO, SUM(SAL) AS "급여 합계" FROM EMP GROUP BY DEPTNO;
SELECT DEPTNO, JOB, SUM(SAL) AS "급여 합계" FROM EMP GROUP BY DEPTNO, JOB;
SELECT DEPTNO, COUNT(*) AS "부서별 인원수" FROM EMP GROUP BY DEPTNO;
SELECT JOB, COUNT(*) AS "직책별 인원수" FROM EMP GROUP BY JOB;
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP 
GROUP BY DEPTNO, JOB HAVING AVG(SAL) >= 2000; 
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP WHERE SAL <=3000 GROUP BY DEPTNO, JOB HAVING AVG(SAL) >= 2000;
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP;