SELECT * FROM EMP; 
SELECT EMPNO, ENAME, DEPTNO, DNAME, LDC
  FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO;

SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;

SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND D.LOC = 'CHICAGO';

SELECT E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND E.SAL<=2500
  AND E.EMPNO<=9999; 

SELECT * 
 FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.ENAME
  FROM EMP E1, EMP E2 
WHERE E1.MGR = E2.EMPNO; 

SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.ENAME
  FROM EMP E1, EMP E2 
WHERE E1.MGR = E2.EMPNO(+);

SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.ENAME
  FROM EMP E1, EMP E2 
WHERE E1.MGR(+) = E2.EMPNO; 

SELECT E1.EMPNO, E1.ENAME, E1.MGR, 
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
  FROM EMP E1, EMP E2 
WHERE E1.MGR = E2.EMPNO;   

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
  FROM EMP E1, EMP E2 
WHERE E1.MGR = E2.EMPNO(+);

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
   FROM EMP E1, EMP E2 
WHERE E1.MGR(+) = E2.EMPNO;