SELECT * FROM EMP, SALGRADE S, DEPT_TEMP;
SELECT * FROM EMP 
WHERE SAL > (SELECT SAL 
            FROM EMP 
            WHERE ENAME = 'JONES');

SELECT * FROM EMP 
WHERE HIREDATE < (SELECT HIREDATE
                  FROM EMP 
                 WHERE ENAME = 'SCOTT');

SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, D.DEPTNO, D.DNAME, D.LOC
   FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO    
AND E.DEPTNO = 20 
AND E.SAL < (SELECT AVG(SAL)
             FROM EMP); 

SELECT * FROM EMP 
WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL)
                    FROM EMP 
                    GROUP BY DEPTNO);  

SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC 
  FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E10, 
       (SELECT * FROM DEPT) D 
WHERE E10.DEPTNO = D.DEPTNO;

WITH 
E10 AS (SELECT * FROM EMP WHERE DEPTNO = 10), 
D   AS (SELECT * FROM DEPT) 
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC 
   FROM E10, D 
WHERE E10.DEPTNO = D.DEPTNO;  

SELECT EMPNO, ENAME, JOB, SAL,
              (SELECT GRADE
                 FROM SALGRADE
                WHERE E.SAL BETWEEN LOSAL AND HISAL) AS SALGRADE,
                DEPTNO,
              (SELECT DNAME
                FROM DEPT
               WHERE E.DEPTNO = DEPT.DEPTNO) AS DNAME
FROM EMP E;