SELECT * FROM EMP, DEPT_TEMP; 
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
            VALUES(50, 'DATABASE', 'SEOUL');
SELECT * FROM  DEPT_TEMP;

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
            VALUES(60, 'NEWYORK' );

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
            VALUES(60, 'NEWYORK', 'WRONG');

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
          VALUES(WRONG, 'NEWYORK', 'BUSAN');

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
          VALUES(600, 'NEWYORK', 'BUSAN');

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
            VALUES(60, 'NEWYORK', 'BUSAN');
SELECT * FROM  DEPT_TEMP;

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
            VALUES(70, 'WEB', NULL);
SELECT * FROM  DEPT_TEMP;

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
            VALUES(80, 'MOBILE', '');
SELECT * FROM  DEPT_TEMP;

CREATE TABLE DEPT_TEMP2
 AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TEMP2;

UPDATE DEPT_TEMP2
   SET LOC = 'SEOUL' ;
SELECT * FROM DEPT_TEMP2;

ROLLBACK;

UPDATE DEPT_TEMP2 
   SET DNAME = 'DATEBASE', 
       LOC = 'SEOUL'
WHERE DEPTNO = 40;
SELECT * FROM DEPT_TEMP2;

CREATE TABLE EMP_TEMP AS SELECT * FROM EMP;

UPDATE EMP_TEMP 
  SET COMM = 50
WHERE SAL <=2500;

UPDATE DEPT_TEMP2 
  SET DNAME = (SELECT DNAME 
               FROM DEPT 
               WHERE DEPTNO = 40),
     LOC = (SELECT LOC 
           FROM DEPT 
             WHERE DEPTNO =40)
WHERE DEPTNO = 40;

CREATE TABLE EMP_TEMP2
 AS SELECT * FROM EMP;
SELECT * FROM EMP_TEMP2;

DELETE FROM EMP_TEMP2
  WHERE JOB = 'MANAGER';
SELECT * FROM EMP_TEMP2;

DELETE FROM EMP_TEMP2 
 WHERE EMPNO IN (SELECT E.EMPNO
                 FROM EMP_TEMP2 E, SALGRADE S 
                 WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                 AND S.GRADE = 3
                 AND DEPTNO = 30);
SELECT * FROM EMP_TEMP2;

DELETE FROM EMP_TEMP2 
 WHERE SAL<=3000;