CREATE TABLE EMP_DDL(
 EMPNO NUMBER(4),
 ENAME VARCHAR(2),
 JOB   VARCHAR(9),
 MGR   NUMBER(4),
 HIREDATE DATE,
 SAL   NUMBER(7,2),
 COMM  NUMBER(7,2),
 DEPTNO NUMBER(2)
);
DESC EMP_DDL;

CREATE TABLE EMP_ALTER
     AS SELECT * FROM EMP; 
SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
  ADD HP VARCHAR2(20);
SELECT * FROM EMP_ALTER; 

ALTER TABLE EMP_ALTER
  RENAME COLUMN HP TO TEL;
SELECT * FROM EMP_ALTER; 

CREATE TABLE TABLE_NOTNULL(
      LOGIN_ID VARCHAR2(20) NOT NULL,
      LOGIN_PWD VARCHAR2(20) NOT NULL,
      TEL       VARCHAR2(20)
);
DESC TABLE_NOTNULL;

      
INSERT INTO TABLE_NOTNULL(LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('TEST_ID_01', NULL, '010-1234-5678');

ALTER TABLE TABLE_NOTNULL
MODIFY(TEL NOT NULL);

CREATE TABLE TABLE_UNIQUE(
      LOGIN_ID VARCHAR2(20) NOT NULL,
      LOGIN_PWD VARCHAR2(20) NOT NULL,
      TEL       VARCHAR2(20)
);
DESC TABLE_UNIQUE;

INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('TEST_ID_01', 'PW01', '010-1234-5678');

SELECT * FROM TABLE_UNIQUE;

INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('TEST_ID_02', 'PW01', '010-1234-5678');

SELECT * FROM TABLE_UNIQUE;

INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('NULL', 'PW01', '010-1234-5678');

SELECT * FROM TABLE_UNIQUE;

ALTER TABLE TABLE_UNIQUE
MODIFY(TEL UNIQUE);

CREATE TABLE TABLE_PK(
      LOGIN_ID VARCHAR2(20) PRIMARY KEY,
      LOGIN_PWD VARCHAR2(20) NOT NULL,
      TEL       VARCHAR2(20)
);
DESC TABLE_PK;

SELECT OWNER CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
  FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_PK%';

SELECT INDEX_NAME, TABLE_OWNER, TABLE_NAME
   FROM USER_INDEXES 
WHERE TABLE_NAME LIKE 'TABLE_PK%';

CREATE TABLE DEPT_FK(
 DEPTNO NUMBER(2) CONSTRAINT DEPTFK_PEPTNO_PK PRIMARY KEY,
 DNAME VARCHAR2(14),
 LOC   VARCHAR2(13)
);
DESC DEPT_FK;

CREATE TABLE EMP_FK (
    EMPNO    NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME    VARCHAR2(10),
    JOB      VARCHAR2(9),
    MGR      NUMBER(4),
    HIREDATE DATE,
    SAL      NUMBER(7,2),
    COMM     NUMBER(7,2),
    DEPTNO   NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK (DEPTNO)
);
DESC EMP_FK;

INSERT INTO EMP_FK
VALUES(9999, 'TEST_NAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01', 'YYYY/MM/DD'),
       3000, NULL, 10);

INSERT INTO DEPT_FK
VALUES(10, 'TEST_DNAME', 'TEST_LOC');
SELECT * FROM DEPT_FK;

INSERT INTO EMP_FK
VALUES(9999, 'TEST_NAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01', 'YYYY/MM/DD'),
       3000, NULL, 10);
SELECT * FROM EMP_FK;

DELETE FROM DEPT_FK
WHERE DEDTNO = 10;

CREATE TABLE TABLE_CHECK(
      LOGIN_ID VARCHAR2(20) CONSTRAINT TBLACK_LOGINID_PK PRIMARY KEY,
      LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLACK_LOGINPW_CK CHECK (LENGTH(LOGIN_PWD)>3),
      TEL       VARCHAR2(20)
);
DESC TABLE_CHECK;

INSERT INTO TABLE_CHECK
VALUES ('TEST_ID', '123', '010-1234-5678');

INSERT INTO TABLE_CHECK
VALUES ('TEST_ID', '1234', '010-1234-5678');
SELECT * FROM TABLE_CHECK;

SELECT OWNER CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
  FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_CHECK';

CREATE TABLE TABLE_DEFAULT(
      LOGIN_ID VARCHAR2(20) CONSTRAINT TBLACK2_LOGINID_PK PRIMARY KEY,
      LOGIN_PWD VARCHAR2(20) DEFAULT '1234',
      TEL       VARCHAR2(20)
);
DESC TABLE_DEFAULT;

INSERT INTO TABLE_DEFAULT
VALUES('TEST_ID', NULL, '010-1234-5678');
INSERT INTO TABLE_DEFAULT
(LOGIN_ID, TEL)
VALUES('TEST_ID2', '010-1234-5678');
SELECT * FROM TABLE_DEFAULT;