CREATE SEQUENCE SEQ_DEDT_SEQUENCE 
  INCREMENT BY 10
  START WITH 10
  MAXVALUE 90
  MINVALUE 0
  NOCYCLE
  CACHE 2;
SELECT * FROM USER_SEQUENCES;

CREATE TABLE DEPT_SEQUENCE (
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13)
);
SELECT * FROM DEPT_SEQUENCE;

INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
VALUES (SEQ_DEDT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');
SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO; 

SELECT SEQ_DEDT_SEQUENCE.CURRVAL FROM DUAL;

ALTER SEQUENCE SEQ_DEDT_SEQUENCE
INCREMENT BY 3
MAXVALUE 99
CYCLE;

SELECT * FROM USER_SEQUENCES;

CREATE TABLE CAR_RENTAL_COMPANY_CAR (
    CAR_ID NUMBER,
    CAR_TYPE VARCHAR2(10),
    DAILY_FEE NUMBER
);
SELECT * FROM CAR_RENTAL_COMPANY_CAR;

INSERT INTO CAR_RENTAL_COMPANY_CAR VALUES (1, '세단', 16000);
INSERT INTO CAR_RENTAL_COMPANY_CAR VALUES (2, 'SUV', 14000);
INSERT INTO CAR_RENTAL_COMPANY_CAR VALUES (3, 'SUV', 22000);

SELECT * FROM CAR_RENTAL_COMPANY_CAR;

SELECT ROUND(AVG(DAILY_FEE), 0) AS AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV';