SELECT DISTINCT JOB FROM EMP;
SELECT DISTINCT JOB, DEPTNO fROM EMP;
SELECT JOB, DEPTNO FROM EMP;
SELECT DISTINCT DEPTNO FROM EMP;
SELECT DISTINCT JOB, DEPTNO fROM EMP;
SELECT DISTINCT SAL FROM EMP;
SELECT DISTINCT JOB, DEPTNO, SAL FROM EMP;