SELECT EMPNO, ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 240) AS WORK20YEAR FROM EMP;
SELECT TO_DATE('2024-08-14','YYYY-MM-DD') AS TODATE1, TO_DATE('2024/08/14','YYYY/MM/DD') AS TODATE2 FROM DUAL;
SELECT EMPNO, ENAME, HIREDATE, TRUNC(SYSDATE - HIREDATE) AS "근무일수" FROM EMP;
SELECT EMPNO, ENAME, HIREDATE, TRUNC(HIREDATE - (SELECT MIN(HIREDATE) FROM EMP)) AS "입사차이일수" FROM EMP WHERE HIREDATE - (SELECT MIN(HIREDATE) FROM EMP) >= 365 ORDER BY HIREDATE;
SELECT EMPNO, ENAME, COMM, NVL2(COMM, 'O', 'X'), NVL2(COMM, SAL*12+COMM, SAL*12) AS 연봉 FROM EMP;
SELECT EMPNO, ENAME, COMM, NVL2(COMM, 'O', 'X') AS "수령여부1", DECODE(COMM, 0, 'X', NULL, 'X', 'O') AS "수령여부2", NVL2(COMM, SAL * 12 + COMM, SAL * 12) AS 연봉 FROM EMP;
SELECT EMPNO, ENAME, JOB, SAL, DECODE(JOB, 'MANAGER', SAL*1.1, 'SALESMAAN', SAL*1.05, 'ANALYST', SAL, SAL*1.03) AS UPSAL FROM EMP;
SELECT EMPNO, ENAME, JOB, SAL, CASE JOB WHEN 'MANAGER' THEN 'NO.1' WHEN 'SALESMAN' THEN 'NO.2' WHEN 'ANALYST'  THEN 'NO.3' ELSE 'NO.4' END AS UPSAL FROM EMP;
SELECT EMPNO, ENAME, COMM, CASE WHEN COMM IS NULL THEN '해당 사항 없음' WHEN COMM = 0 THEN '수당 없음' WHEN COMM > 0 THEN '수당 :   ' || COMM END AS COMM_TEXT FROM EMP;

SELECT EMPNO, RPAD(SUBSTR(TO_CHAR(EMPNO), 1, 2), 4, '*') AS MASKING_EMPNO, ENAME, RPAD(SUBSTR(ENAME, 1, 1), LENGTH(ENAME), '*') AS MASKING_ENAME FROM EMP WHERE LENGTH(ENAME) >= 5 AND LENGTH(ENAME) < 6;
SELECT EMPNO, ENAME, SAL, TRUNC(SAL / 21.5, 2) AS DAY_PAY,ROUND((SAL / 21.5) / 8, 1) AS TIME_PAY FROM EMP;
SELECT EMPNO, ENAME, HIREDATE, TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3), '월요일'), 'YYYY-MM-DD') AS R_JOB, NVL(TO_CHAR(COMM), 'N/A') AS COMM FROM EMP;
SELECT EMPNO, ENAME, MGR, CASE WHEN MGR IS NULL THEN '0000' WHEN SUBSTR(TO_CHAR(MGR), 1, 2) = '75' THEN '5555' WHEN SUBSTR(TO_CHAR(MGR), 1, 2) = '76' THEN '6666' WHEN SUBSTR(TO_CHAR(MGR), 1, 2) = '77' THEN '7777' WHEN SUBSTR(TO_CHAR(MGR), 1, 2) = '78' THEN '8888' ELSE TO_CHAR(MGR) END AS CHG_MGR FROM EMP;