SELECT * FROM EMP 
WHERE DEPTNO = 30 AND SAL >= 1600;
SELECT * FROM EMP 
WHERE JOB = 'MANAGER' OR JOB = 'ANALYST';
SELECT * FROM EMP 
WHERE (DEPTNO = 10 OR DEPTNO = 20) AND JOB = 'CLERK';
SELECT * FROM EMP 
WHERE SAL >= 1500 AND COMM IS NOT NULL;
SELECT * FROM EMP 
WHERE JOB = 'SALESMAN' OR SAL >= 3000;
SELECT * FROM EMP 
WHERE DEPTNO IN (10, 20, 30) AND SAL >= 2000;