SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
  FROM EMP E 
  JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
 WHERE D.LOC = 'CHICAGO';

SELECT *
  FROM EMP E
  JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL);

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
  FROM EMP E1
  JOIN EMP E2 ON (E1.MGR = E2.EMPNO);

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
  FROM EMP E1
  LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO);

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
  FROM EMP E1
  RIGHT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO);

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
       DEPTNO, D.DNAME, D.LOC
  FROM EMP E JOIN DEPT D USING (DEPTNO)
 WHERE E.SAL >= 3000
   AND E.MGR IS NOT NULL
 ORDER BY DEPTNO, E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
       E.DEPTNO, D.DNAME, D.LOC  
  FROM EMP E 
  JOIN DEPT D ON (E.DEPTNO = D.DEPTNO) 
 WHERE E.SAL >= 3000
   AND E.MGR IS NOT NULL
 ORDER BY E.DEPTNO, E.EMPNO;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND E.SAL > 2000;

SELECT D.DEPTNO, D.DNAME, 
       TRUNC(AVG(E.SAL)) AS AVG_SAL, MAX(E.SAL) AS MAX_SAL, 
       MIN(E.SAL) AS MIN_SAL, COUNT(*) AS CNT
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO(+)
ORDER BY D.DEPTNO, E.ENAME;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL, S.GRADE,
       M.EMPNO AS MGR_EMPNO, 
       M.ENAME AS MGR_ENAME
  FROM DEPT D, EMP E, SALGRADE S, EMP M
 WHERE D.DEPTNO = E.DEPTNO(+)        
   AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+) 
   AND E.MGR = M.EMPNO(+)           
 ORDER BY D.DEPTNO, E.EMPNO;

SELECT DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E JOIN DEPT D USING (DEPTNO)
WHERE E.SAL > 2000;

SELECT DEPTNO, D.DNAME, 
       TRUNC(AVG(E.SAL)) AS AVG_SAL, MAX(E.SAL) AS MAX_SAL, 
       MIN(E.SAL) AS MIN_SAL, COUNT(*) AS CNT
FROM EMP E JOIN DEPT D USING (DEPTNO)
GROUP BY DEPTNO, D.DNAME;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM DEPT D LEFT OUTER JOIN EMP E ON (D.DEPTNO = E.DEPTNO)
ORDER BY D.DEPTNO, E.ENAME;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL, S.GRADE,
       M.EMPNO AS MGR_EMPNO, M.ENAME AS MGR_ENAME
FROM DEPT D 
LEFT OUTER JOIN EMP E ON (D.DEPTNO = E.DEPTNO)
LEFT OUTER JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
LEFT OUTER JOIN EMP M ON (E.MGR = M.EMPNO)
ORDER BY D.DEPTNO, E.EMPNO;