SELECT MAX(SAL) FROM EMP WHERE DEPTNO = 10 UNION SELECT MIN(SAL) FROM EMP WHERE DEPTNO = 10;
SELECT DEPTNO, ROUND(AVG(SAL), 2) AS "부서별 평균" FROM EMP WHERE DEPTNO IN (10, 20, 30) GROUP BY DEPTNO;

SELECT DEPTNO,TRUNC(AVG(SAL)) AS AVG_SAL, MAX(SAL) AS MAX_SAL, MIN(SAL) AS MIN_SAL, COUNT(*) AS CNT FROM EMP GROUP BY DEPTNO;
SELECT JOB, COUNT(*) AS CNT FROM EMP GROUP BY JOB HAVING COUNT(*) >=3;
SELECT TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR, DEPTNO, COUNT(*) AS CNT FROM EMP GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO ORDER BY HIRE_YEAR DESC;
SELECT NVL2(COMM, 'O', 'X') AS EXIST_COMM, COUNT(*) AS CNT FROM EMP GROUP BY NVL2(COMM, 'O', 'X');                                            