SELECT * FROM EMP 
WHERE JOB = 'CLERK' 
AND SAL BETWEEN 1000 AND 1500;
SELECT ENAME, JOB 
FROM EMP 
WHERE ENAME LIKE '%AM%';
SELECT * FROM EMP 
WHERE DEPTNO = 10 
AND (JOB != 'MANAGER' OR MGR IS NULL);