SELECT ENAME, LENGTH(ENAME) AS 이름길이 FROM EMP WHERE LENGTH(ENAME) <= 5;
SELECT JOB, SUBSTR(JOB, 3, 2) FROM EMP; 
SELECT JOB, SUBSTR(JOB, -3, 2) FROM EMP; 
SELECT JOB, SUBSTR(JOB, -LENGTH(JOB)) FROM EMP;
SELECT JOB, INSTR(JOB, 'A') AS A의위치 FROM EMP;
SELECT * FROM EMP WHERE INSTR(ENAME, 'S') > 0;
SELECT * FROM EMP WHERE ENAME LIKE '%S%';
SELECT REPLACE('010-1234-5678', '-', '') AS PHONE_NUMBER FROM DUAL;
SELECT SUBSTR('010-1234-5678', 5, 4) AS MIDDLE_NUM, SUBSTR('010-1234-5678', 10, 4) AS LAST_NUM FROM DUAL;