SELECT * FROM EMP ORDER BY SAL ASC;
SELECT * FROM EMP ORDER BY SAL DESC;
SELECT * FROM EMP ORDER BY DEPTNO ASC, SAL DESC;
SELECT ENAME, SAL FROM EMP ORDER BY SAL;
SELECT * FROM EMP ORDER BY HIREDATE DESC;
SELECT * FROM EMP ORDER BY DEPTNO ASC, ENAME DESC;
SELECT * FROM EMP ORDER BY COMM DESC, SAL ASC;
SELECT ENAME, DEPTNO, SAL FROM EMP ORDER BY SAL DESC;
SELECT * FROM SALGRADE ORDER BY GRADE ASC, HISAL DESC;